[package]
name = "tuwunel_api_admin"
categories.workspace = true
description.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[lib]
path = "mod.rs"
bench = false
crate-type = [
	"rlib",
#	"dylib",
]

[dependencies]
axum.workspace = true
const-str.workspace = true
ctor.workspace = true
dtor.workspace = true
futures.workspace = true
hmac.workspace = true
itertools.workspace = true
ruma.workspace = true
serde.workspace = true
serde_json.workspace = true
sha1.workspace = true
synapse-admin-api.workspace = true
tracing.workspace = true
tuwunel-api.workspace = true
tuwunel-api-client.workspace = true
tuwunel-core.workspace = true
tuwunel-matrix.workspace = true
tuwunel-service.workspace = true

[lints]
workspace = true
